version: '3.7'
services:
  percona2:
    image: percona:8.0.20-11
    environment:
      MYSQL_DATABASE: ccart
      MYSQL_ROOT_PASSWORD: root
    # volumes:
    #   - ./dev/mysql:/var/lib/mysql:rw
    command: ['--default-authentication-plugin=mysql_native_password']
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8090:8080
  redmine2:
    image: redmine:4.1
    ports:
      - 8080:3000
    volumes:
      # - ./dev/redmine/files:/usr/src/redmine/files
      - ./config.yml:/usr/src/redmine/config/configuration.yml
    environment:
      REDMINE_DB_MYSQL: redmine_percona2_1
      REDMINE_DB_PASSWORD: root
      REDMINE_DB_DATABASE: redmine
